### ISSUE TITLE
Host not found

### ISSUE THREAD

**Issue by juneeighteen** [aaraney/usgs-stream-mapper#3]
👋 I tried installing this plugin for the first time today, and seeing an error (plugin version 0.2, QGIS version 3.26.2-Buenos Aires) 

```
AttributeError: 'NoneType' object has no attribute 'symbol' 
Traceback (most recent call last):
  File "/Users/drew/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/usgs_stream_mapper/usgs_stream_mapper.py", line 273, in run
    usgs_layer.renderer().symbol().setColor(QColor('green'))
AttributeError: 'NoneType' object has no attribute 'symbol'
```

**Comment by aaraney** [comment]
Hi @juneeighteen! Thanks for reporting this! 

I'll try to take a look at this over the weekend and update the issue accordingly.

**Comment by aaraney** [comment]
After looking into this @juneeighteen, I was able to reproduce this when I provided an invalid USGS site code or disconnected from the network. Admittedly, this is not the most useful error message, so Ill try to improve this error message handling.

@juneeighteen, can you reproduce this when you provide a valid USGS site code? 02465000 worked for me.
